name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Fetch specific branch
              run: git fetch origin main:main

            - name: Install Dependencies
              run: ./run install

            - name: Run tests
              run: ./run test
