name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Give execute permissions to ./run
              run: chmod +x ./run

            - name: Install Dependencies
              run: ./run install

            - name: Run tests
              run: ./run test

    lint-typescript:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Give execute permissions to ./run
              run: chmod +x ./run

            - name: Install Dependencies
              run: ./run install

            - name: Lint TypeScript
              run: npx eslint '**/*.ts'
